### ISSUE TITLE
Getting Bad request errors when requesting google sheet reader

### ISSUE THREAD

**Issue by bashaasnoot** [emirn/google_sheet_reader_bot#1]
Hello,
I'm testing this project using c9.io but I'm getting http 400 errors when doing a request on the spreadsheet, is the url to the spreadsheet still correct?
When executing that url in a browser I get the message: "Invalid query parameter value for grid_i"

**Comment by emirn** [comment]
@bashaasnoot have you published the Google sheet? It should be published via File - Publish To Web. 
If you just set the sheet to be public then it will not work, it is obligatory to set Published To Web to be able to get JSON from that sheet

**Comment by bashaasnoot** [comment]
Hi Emirn,

Thanks for your reply.
I did publish the Google sheet, the probleem was the '/od6/' part of the url, which seems to be the grid_id.
After I changed this to '1' it worked like a charm.

Thanks for this awesome project!

**Comment by emirn** [comment]
thank you for sharing the solution! will close this issue
